dev_lite:
    # DB: sqlite:///server/langman.db 
    DB_USAGE: sqlite:///server/usages.db
    DB_GAMES: sqlite:///server/langman.db
    DB_AUTH:  sqlite:///server/langman.db

dev_postgres:
    DB_USAGE: sqlite:///server/usages.db
    DB_GAMES: postgresql://postgres:fkrt.1234@localhost:5432/langman
    DB_AUTH:  postgresql://postgres:fkrt.1234@localhost:5432/langman

heroku:
    DB_USAGE: sqlite:///server/usages.db
    DB_GAMES: env:DATABASE_URL
    DB_AUTH:  env:DATABASE_URL